spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jobdb
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  webhook:
    generate-url: https://bfhldevapigw.healthrx.co.in/hiring/generateWebhook/JAVA
